name: Secrets Management Pipeline

on:
  push:
    branches:
      - feature/secrets-management

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: capstone-eks

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Secret from AWS Secrets Manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id capstone/app/database \
            --query SecretString \
            --output text)

          echo "DB_USERNAME=$(echo $SECRET | jq -r '.DB_USERNAME')" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(echo $SECRET | jq -r '.DB_PASSWORD')" >> $GITHUB_ENV

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      - name: Create K8s Secret
        run: |
          kubectl create secret generic capstone-db-secret \
            --from-literal=DB_USERNAME="$DB_USERNAME" \
            --from-literal=DB_PASSWORD="$DB_PASSWORD" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Verify Secret Created
        run: |
          kubectl get secret capstone-db-secret